using Centuri.Demo.Models;
namespace Centuri.Demo.Services;

public class DocumentService : IDocumentService
{
    private static readonly IReadOnlyList<Document> Documents = new List<Document>
    {
        new() { Id = 1,  Title = "SOP-001: Deviation Handling Procedure",         Content = "This procedure describes the process for reporting, investigating, and resolving deviations from established quality standards.",                Category = "SOP",    Version = 3, Status = DocumentStatus.Approved,  CreatedBy = "Anna Lindberg",    CreatedAt = new DateTime(2024, 1, 15), UpdatedAt = new DateTime(2025, 6, 10) },
        new() { Id = 2,  Title = "SOP-002: Document Control Procedure",           Content = "Defines the lifecycle of controlled documents including creation, review, approval, distribution, and retirement.",                             Category = "SOP",    Version = 2, Status = DocumentStatus.Approved,  CreatedBy = "Erik Johansson",   CreatedAt = new DateTime(2024, 2, 1),  UpdatedAt = new DateTime(2025, 3, 20) },
        new() { Id = 3,  Title = "SOP-003: Internal Audit Procedure",             Content = "Describes how internal audits are planned, conducted, reported, and followed up to ensure compliance with the quality management system.",      Category = "SOP",    Version = 4, Status = DocumentStatus.Approved,  CreatedBy = "Anna Lindberg",    CreatedAt = new DateTime(2023, 11, 5), UpdatedAt = new DateTime(2025, 9, 1) },
        new() { Id = 4,  Title = "SOP-004: CAPA Management Procedure",            Content = "Outlines the corrective and preventive action process including root cause analysis, action planning, and effectiveness verification.",          Category = "SOP",    Version = 2, Status = DocumentStatus.InReview,  CreatedBy = "Maria Karlsson",   CreatedAt = new DateTime(2024, 5, 12), UpdatedAt = new DateTime(2026, 1, 15) },
        new() { Id = 5,  Title = "SOP-005: Supplier Qualification Procedure",     Content = "Defines the criteria and process for evaluating, approving, and monitoring suppliers of materials and services.",                                  Category = "SOP",    Version = 1, Status = DocumentStatus.Draft,     CreatedBy = "Lars Pettersson",  CreatedAt = new DateTime(2025, 10, 1), UpdatedAt = new DateTime(2025, 10, 1) },
        new() { Id = 6,  Title = "QM-001: Quality Manual",                        Content = "Top-level document describing the quality management system scope, policy, objectives, and organizational structure.",                             Category = "Manual", Version = 5, Status = DocumentStatus.Approved,  CreatedBy = "Anna Lindberg",    CreatedAt = new DateTime(2022, 3, 1),  UpdatedAt = new DateTime(2025, 12, 1) },
        new() { Id = 7,  Title = "QM-002: Management Review Process",             Content = "Describes inputs, outputs, and frequency of management reviews to ensure continuing suitability and effectiveness of the QMS.",                   Category = "Manual", Version = 2, Status = DocumentStatus.Approved,  CreatedBy = "Erik Johansson",   CreatedAt = new DateTime(2023, 6, 15), UpdatedAt = new DateTime(2025, 6, 15) },
        new() { Id = 8,  Title = "QM-003: Internal Audit Process",                Content = "High-level process description for the internal audit programme aligned with ISO 19011 guidelines.",                                               Category = "Manual", Version = 3, Status = DocumentStatus.Approved,  CreatedBy = "Anna Lindberg",    CreatedAt = new DateTime(2023, 1, 10), UpdatedAt = new DateTime(2025, 8, 20) },
        new() { Id = 9,  Title = "WI-001: Incoming Goods Inspection",             Content = "Step-by-step work instruction for inspecting raw materials and components upon receipt at the warehouse.",                                          Category = "WI",     Version = 2, Status = DocumentStatus.Approved,  CreatedBy = "Sofia Andersson",  CreatedAt = new DateTime(2024, 4, 20), UpdatedAt = new DateTime(2025, 4, 20) },
        new() { Id = 10, Title = "WI-002: Environmental Monitoring",              Content = "Work instruction for monitoring temperature, humidity, and particulate levels in controlled production areas.",                                      Category = "WI",     Version = 1, Status = DocumentStatus.InReview,  CreatedBy = "Nils Eriksson",    CreatedAt = new DateTime(2025, 7, 1),  UpdatedAt = new DateTime(2025, 11, 5) },
        new() { Id = 11, Title = "WI-012: Equipment Calibration",                 Content = "Detailed instructions for calibrating measurement and test equipment including acceptance criteria and calibration intervals.",                     Category = "WI",     Version = 3, Status = DocumentStatus.Approved,  CreatedBy = "Lars Pettersson",  CreatedAt = new DateTime(2023, 9, 1),  UpdatedAt = new DateTime(2025, 9, 1) },
        new() { Id = 12, Title = "WI-013: Batch Record Review",                   Content = "Instructions for reviewing batch production records to verify completeness, accuracy, and compliance before product release.",                      Category = "WI",     Version = 2, Status = DocumentStatus.Approved,  CreatedBy = "Maria Karlsson",   CreatedAt = new DateTime(2024, 3, 15), UpdatedAt = new DateTime(2025, 3, 15) },
        new() { Id = 13, Title = "POL-001: Data Integrity Policy",                Content = "Establishes principles and expectations for ensuring data integrity across all GxP-regulated computerized systems.",                               Category = "Policy", Version = 1, Status = DocumentStatus.Approved,  CreatedBy = "Erik Johansson",   CreatedAt = new DateTime(2024, 8, 1),  UpdatedAt = new DateTime(2024, 8, 1) },
        new() { Id = 14, Title = "POL-002: Quality Policy",                       Content = "States the organization's commitment to quality, customer satisfaction, regulatory compliance, and continuous improvement.",                         Category = "Policy", Version = 4, Status = DocumentStatus.Approved,  CreatedBy = "Anna Lindberg",    CreatedAt = new DateTime(2021, 1, 1),  UpdatedAt = new DateTime(2025, 1, 1) },
        new() { Id = 15, Title = "POL-003: Training and Competence Policy",       Content = "Defines requirements for training, qualification, and ongoing competence assessment of personnel performing quality-critical activities.",           Category = "Policy", Version = 2, Status = DocumentStatus.Approved,  CreatedBy = "Sofia Andersson",  CreatedAt = new DateTime(2023, 5, 1),  UpdatedAt = new DateTime(2025, 5, 1) },
        new() { Id = 16, Title = "FORM-001: Deviation Report Template",           Content = "Standardized form for documenting deviation details, root cause investigation, and corrective actions.",                                             Category = "Form",   Version = 3, Status = DocumentStatus.Approved,  CreatedBy = "Maria Karlsson",   CreatedAt = new DateTime(2024, 1, 1),  UpdatedAt = new DateTime(2025, 7, 1) },
        new() { Id = 17, Title = "FORM-002: Change Request Form",                 Content = "Form used to initiate, evaluate, and approve changes to processes, equipment, materials, or documents.",                                             Category = "Form",   Version = 2, Status = DocumentStatus.Approved,  CreatedBy = "Erik Johansson",   CreatedAt = new DateTime(2024, 6, 1),  UpdatedAt = new DateTime(2025, 6, 1) },
        new() { Id = 18, Title = "FORM-003: Audit Checklist Template",            Content = "Configurable checklist template for planning and conducting internal and external quality audits.",                                                   Category = "Form",   Version = 1, Status = DocumentStatus.Draft,     CreatedBy = "Nils Eriksson",    CreatedAt = new DateTime(2025, 11, 1), UpdatedAt = new DateTime(2025, 11, 1) },
        new() { Id = 19, Title = "SOP-006: Change Control Procedure",             Content = "Procedure for managing changes to validated systems, processes, and facilities including impact assessment and implementation planning.",            Category = "SOP",    Version = 1, Status = DocumentStatus.InReview,  CreatedBy = "Lars Pettersson",  CreatedAt = new DateTime(2025, 8, 15), UpdatedAt = new DateTime(2026, 2, 1) },
        new() { Id = 20, Title = "SOP-007: Risk Management Procedure",            Content = "Describes the methodology for identifying, assessing, mitigating, and monitoring quality risks using FMEA and risk matrix approaches.",            Category = "SOP",    Version = 2, Status = DocumentStatus.Archived,  CreatedBy = "Anna Lindberg",    CreatedAt = new DateTime(2023, 4, 1),  UpdatedAt = new DateTime(2025, 4, 1) },
    };

    public Task<IEnumerable<Document>> GetAllAsync()
        => Task.FromResult<IEnumerable<Document>>(Documents);

    public Task<Document?> GetByIdAsync(int id)
        => Task.FromResult(Documents.FirstOrDefault(d => d.Id == id));

    public Task<int> GetCountAsync()
        => Task.FromResult(Documents.Count);

    public Task<(IEnumerable<Document> Documents, bool Truncated)> ExportAsync(int maxRows = 10_000)
    {
        var truncated = Documents.Count > maxRows;
        var result = truncated ? Documents.Take(maxRows) : Documents;
        return Task.FromResult((result.AsEnumerable(), truncated));
    }
}
